### PR TITLE
load workspace from workspace-url URL param

### PR DESCRIPTION
**Pull request by lmvdz**
Load workspace from URL using `?workspace-url=<url>` 
Tested with `?workspace-url=https://raw.githubusercontent.com/RealmixSoda/aggr/main/gkds_realmix-watch-v2.txt`

### CODE REVIEW

**Comment by lmvdz** [comment]
This PR has extra shit leftover from the Serum repo... You probably just want the last commit.

**Comment by lmvdz** [comment]
Load existing workspace to avoid prompt, will get annoying... and for some reason when importing workspace with existing ID, aggr lags out

**Comment by lmvdz** [comment]
0fd4709260a7aaf8fdae22bbe03f52a1

**Comment by adeacetis** [comment]
Hey @Tucsky,

This PR is almost 9+ months old and requires extra work to make it mergeable worthy.

how do you feel about this feature finally?
do we add it to the repo? 

If yes, we will have to ask @lmvdz to clean this up and test the new change.

**Comment by lmvdz** [comment]
Not a big deal, not using it regularly.

**Comment by adeacetis** [comment]
Personally, I found out that storing files locally or in the cloud and drag-dropping them onto the chart was enough.

Let's shelve it for now and see if the need for it reappears. Do you agree?

**Pull request closed without merging**
