### PR TITLE
Fix Kraken futures trade feed

### PR DESCRIPTION
**Pull request by adeacetis**
For the pair PF_SOLUSD

1. Kraken Futures platform - pro.kraken.com
image

2. https://charts.aggr.trade/zjqe

It's showing size in SOL instead of the size in USD
image

3. PR changes

Everything seems good now.
image

We'll note another issue if we compare 1-2 is that trades are not showing up in the same order than on the kraken platform. 

Also noticed an issue where time isn't showing two digit minutes (if you choose to display actual time of trades instead of elapsed time since the trade occured). This will be filed separately

### CODE REVIEW

**Comment by Tucsky** [comment]
To me it looks like it's already working
image

maybe they have multiple futures platform but PI_XBTUSD is being traded @ https://futures.kraken.com/trade/futures/PI_XBTUSD and is matching with what they are showing there, couldn't test any alts futures market because, there isn't any volume on any of those

**Comment by adeacetis** [comment]
*PI_* are perpetual inverse listed on a whole different platform called [CryptoFacilities ](https://www.cryptofacilities.com/
) according to the doc.
image

Doc:
https://support.kraken.com/hc/en-us/articles/360022835911-Inverse-Crypto-Collateral-Perpetual-Contract-Specifications

The change I made is for *PF_* prefixed contract trading on pro.kraken.com

**Comment by adeacetis** [comment]
FYI

*PI* pairs in Kraken official doc:
image

Pairs trading on CryptoFacilities:
image

**Comment by Tucsky** [comment]
CryptoFacilities was aquired by Kraken in 4 years ago, it's now the same markets as the url I posted above

KRAKEN:BTC/USD on aggr is Kraken BTCUSD margin trade market https://pro.kraken.com/app/trade/margin-btc-usd
image

**Comment by adeacetis** [comment]
Okay, but then the current code is working for PI pairs not for PF. We need to incorporate a new case.

**Comment by Tucsky** [comment]
I see 
image

Yeah pf_ trades show qty... for consistency showing amount would be better 👍🏼

**Comment by adeacetis** [comment]
PR updated, please review

**Comment by adeacetis** [comment]
What should we do with CryptoFacilities ?
I noticed you do some string manipulations with Futures contract that are actually trading on CryptoFacilities, but nothing on Kraken itself. I wonder if we should actually offer PI_ and FI_ since they aren't trading on the main kraken platform.

image

**Comment by adeacetis** [comment]
I didn't see your link. PI pairs are indeed trading on `futures.kraken.com` as well. They started consolidating both platforms this year but they didn't do the inverted perps. I dont know if they plan on doing it at some point.

Should we add a new filter to separate inverted perps and perp fut?

**Comment by Tucsky** [comment]
> Should we add a new filter to separate inverted perps and perp fut?

Not sure if thats worth the time of studying every contracts on every deriv crypto exchanges supported here to implement the filter that would potentialy slow down the search module

**Review by Tucsky — APPROVED** [review]

**Comment by adeacetis** [comment]
Iunderstand, and yes, it makes sense not spending time to analyze every futures exchange products list.

However, for Kraken, we already have been removing prefixes for PI_ and FI_ pairs (see above). We don't do it for PF_ pairs while I think they are actually more important. PF are what most people trade most of the time.

image

Invert are usually crowded with traders willing to hedge LT holding. Volume is usually low except in a bull market. In the case of Kraken but it is also the case with Deribit, you need to post collateral in the underlying of the contract you're trading. It's important IMO.

Aggr users like aligning volume deltas of spots and perps, and a separation of fut perps and invert perps could also give very different information.

That said, I think we should leave PI_ and FI_ prefixes on the kraken pairs and remove it for PF_ as it is the most traded pair by far - it's more convenient for the majority of traders

**Comment by Tucsky** [comment]
> However, for Kraken, we already have been removing prefixes for PI_ and FI_ pairs (see above).

They are not really removed

image
this code, along with other symbol normalisation formatter allow us to map PI_XBTUSD (remote symbol) with BTCUSD (local symbol)
but it's still accessible via KRAKEN:PI_XBTUSD in scripts or in search (use local symbol turned off), 
so PF need to be added as "group by pair" should NOT show remote symbol (unknown to most user)
image

exchanges are constantly changing things and I didn't knew they added thoses !! :)

**Comment by adeacetis** [comment]
Of course you didn't know ;)

There are hundreds of moving parts and it's constantly changing as you said.

Glad we've sorted out that one since I am using Kraken a lot lately ;)

**Pull request merged**
