### PR TITLE
Serum (Solana) exchange support

### PR DESCRIPTION
**Pull request by lmvdz**
Hi @Tucsky,

I've added Serum exchange in this PR.

A couple of things need to be done to get this to work:

```javascript
// This will generate a valid market.json to use with serum-vial
const axios = require('axios')
const solana_token_list_url = 'https://raw.githubusercontent.com/solana-labs/token-list/main/src/tokens/solana.tokenlist.json';
const { Connection, PublicKey, clusterApiUrl } = require('@solana/web3.js');
const  { Market } = require('@project-serum/serum');
const fs = require('fs');
let connection = new Connection(clusterApiUrl('mainnet-beta'));


const programAddress = new PublicKey("9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"); // Serum v3 market program id


const serum_vial_market_template = {
    "name": "",
    "baseMintAddress": "",
    "quoteMintAddress": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "version": 3,
    "address": "",
    "programId": "",
    "baseCurrency": "",
    "quoteCurrency": "USDC",
    "tickSize": "",
    "minOrderSize": "",
    "deprecated": ""
}

if (!fs.existsSync('./markets.json')) {
    fs.writeFileSync('./markets.json', JSON.stringify([], null, 4))
}

function getSerumVialMarkets() {
    return new Promise(function(resolve, reject) {
        axios.get(solana_token_list_url).then(response => response.data).then(token_list => {
            token_list.tokens.filter(t => t.chainId === 101 && t.extensions !== undefined && t.extensions.serumV3Usdc !== undefined).forEach((token, index, tokens) => {
                setTimeout(() => {
                    connection.getAccountInfo(new PublicKey(token.extensions.serumV3Usdc)).then((accountInfo) => {
                        if (accountInfo.owner.toBase58() !== programAddress.toBase58()) {
                            console.error(new Error('invalid serumV3Usdc'), token)
                        } else {
                            Market.load(connection, new PublicKey(token.extensions.serumV3Usdc), {}, programAddress).then(market => {
                                const tokenMarket = JSON.parse(JSON.stringify(serum_vial_market_template))
                                tokenMarket.name = token.symbol + "/USDC"
                                tokenMarket.baseMintAddress = token.address;
                                tokenMarket.address = token.extensions.serumV3Usdc;
                                tokenMarket.programId = programAddress.toBase58()
                                tokenMarket.baseCurrency = token.symbol
                                tokenMarket.minOrderSize = market.minOrderSize;
                                tokenMarket.tickSize = market.tickSize;
                                tokenMarket.deprecated = false;
                                const markets = JSON.parse(fs.readFileSync('./markets.json'))
                                if (markets.filter(m => m.baseMintAddress === token.address).length === 0) {
                                    markets.push(tokenMarket)
                                } else {
                                    let existingMarket = markets[markets.indexOf(markets.filter(m => m.address === token.extensions.serumV3Usdc)[0])];
                                    existingMarket = { ...existingMarket, ...tokenMarket }
                                    markets[markets.indexOf(markets.filter(m => m.address === token.extensions.serumV3Usdc)[0])] = existingMarket;
                                }
                                fs.writeFileSync('./markets.json', JSON.stringify(markets, null, 4))
                                console.log('loaded market - ' + tokenMarket.name)
                                if (index === tokens.length - 1) {
                                    resolve(JSON.parse(fs.readFileSync('./markets.json')))
                                }
                            }).catch(error => {
                                console.error(error);
                                console.error(index + " - failed to load", token)
                                if (index === tokens.length - 1) {
                                    resolve(JSON.parse(fs.readFileSync('./markets.json')))
                                }
                            })
                        }
                    })
                }, 1100 * index)
            })
        })
    })
}
```
`npm install -g serum-vial`
`serum-vial --markets-json market.json`
serum-vial by default uses the serumproject solana rpc node https://github.com/tardis-dev/serum-vial
if you want to use your own solana rpc node https://docs.solana.com/running-validator
add the endpoint of serum-vial instance to the cors.aggr.trade

image
image

### CODE REVIEW

**Comment by Tucsky** [comment]
Thank you for the work, why not query the github directly from the serum.ts ?

```
export default class extends Exchange {
  id = 'SERUM'

  protected endpoints = {
    PRODUCTS: 'https://raw.githubusercontent.com/solana-labs/token-list/main/src/tokens/solana.tokenlist.json'
  }

  getUrl() {
    return 'wss://api.serum-vial.dev/v1/ws'
  }

  formatProducts(data) {
    return data.tokens
      .filter(t => t.chainId === 101 && t.extensions !== undefined && t.extensions.serumV3Usdc !== undefined)
      .map(token => token.symbol + '/USDC')
  }

...
```

Just need to ignore proxy configuration when target is raw.githubusercontent.com
I only tested on my local but I was able to get it to work :)

**Comment by lmvdz** [comment]
> Thank you for the work, why not query the github directly from the serum.ts ?
> 
> ```
> export default class extends Exchange {
>   id = 'SERUM'
> 
>   protected endpoints = {
>     PRODUCTS: 'https://raw.githubusercontent.com/solana-labs/token-list/main/src/tokens/solana.tokenlist.json'
>   }
> 
>   getUrl() {
>     return 'wss://api.serum-vial.dev/v1/ws'
>   }
> 
>   formatProducts(data) {
>     return data.tokens
>       .filter(t => t.chainId === 101 && t.extensions !== undefined && t.extensions.serumV3Usdc !== undefined)
>       .map(token => token.symbol + '/USDC')
>       .filter((v, i, a) => a.indexOf(v) === i)
>   }
> 
> ...
> ```
> 
> Just need to ignore proxy configuration when target is raw.githubusercontent.com I only tested on my local but I was able to get it to work :)

So there are a lot of coins excluded from the market.json if you use just the serum-vial provided dev url
The serum-vial needs all the markets from the raw.githubusercontent.com

**Comment by lmvdz** [comment]
https://api.serum-vial.dev/v1/markets - 82 entries
my markets.json script - 156 entries

**Comment by Tucsky** [comment]
> https://api.serum-vial.dev/v1/markets - 82 entries my markets.json script - 156 entries

This is what I get from the github url... 157 pairs

[
    "ECHO/USDC",
    "KITTY/USDC",
    "OTR/USDC",
    "TBK/USDC",
    "BIP/USDC",
    "INU/USDC",
    "WIPE/USDC",
    "SNJ/USDC",
    "ALM/USDC",
    "SWOLE/USDC",
    "BOKU/USDC",
    "OOGI/USDC",
    "SPKL/USDC",
    "TRTLS/USDC",
    "SLX/USDC",
    "SLB/USDC",
    "SOLA/USDC",
    "SOL/USDC",
    "IVN/USDC",
    "BTC/USDC",
    "ETH/USDC",
    "YFI/USDC",
    "LINK/USDC",
    "SUSHI/USDC",
    "ALEPH/USDC",
    "SXP/USDC",
    "HGET/USDC",
    "CREAM/USDC",
    "UBXT/USDC",
    "HNT/USDC",
    "FRONT/USDC",
    "AKRO/USDC",
    "HXRO/USDC",
    "UNI/USDC",
    "SRM/USDC",
    "FTT/USDC",
    "MSRM/USDC",
    "TOMO/USDC",
    "LUA/USDC",
    "MATH/USDC",
    "KEEP/USDC",
    "FIDA/USDC",
    "KIN/USDC",
    "MAPS/USDC",
    "OXY/USDC",
    "USDT/USDC",
    "RAY/USDC",
    "EOSBEAR/USDC",
    "MIDBULL/USDC",
    "METARARITY/USDC",
    "XCOPE/USDC",
    "COPE/USDC",
    "INO/USDC",
    "ROPE/USDC",
    "MEDIA/USDC",
    "STEP/USDC",
    "SAMO/USDC",
    "ATLAS/USDC",
    "POLIS/USDC",
    "DOI/USDC",
    "HOSA/USDC",
    "TCW/USDC",
    "LOST/USDC",
    "LOVE/USDC",
    "MRDR/USDC",
    "PFP/USDC",
    "AVE/USDC",
    "ASF/USDC",
    "TLS/USDC",
    "SPT/USDC",
    "PBA/USDC",
    "UWB/USDC",
    "OMPH/USDC",
    "SATM/USDC",
    "SDOGE/USDC",
    "HOLD/USDC",
    "FROG/USDC",
    "CRT/USDC",
    "SKEM/USDC",
    "SOLAPE/USDC",
    "WOOF/USDC",
    "MER/USDC",
    "LOTTO/USDC",
    "BOLE/USDC",
    "MIT/USDC",
    "AUSS/USDC",
    "TULIP/USDC",
    "KEKW/USDC",
    "DWT/USDC",
    "DOGA/USDC",
    "CHEEMS/USDC",
    "CATO/USDC",
    "NINJA/USDC",
    "LLAMA/USDC",
    "BOP/USDC",
    "DXL/USDC",
    "PIPANA/USDC",
    "KLB/USDC",
    "ORCA/USDC",
    "renBTC/USDC",
    "renBCH/USDC",
    "renDOGE/USDC",
    "renLUNA/USDC",
    "renZEC/USDC",
    "SAIL/USDC",
    "RIN/USDC",
    "POTATO/USDC",
    "STVA/USDC",
    "LIQ/USDC",
    "CRP/USDC",
    "SLRS/USDC",
    "SODA/USDC",
    "SOLBERRY/USDC",
    "CRYN/USDC",
    "SBR/USDC",
    "mSOL/USDC",
    "BET/USDC",
    "PORT/USDC",
    "MNGO/USDC",
    "UPS/USDC",
    "gSAIL/USDC",
    "SUNNY/USDC",
    "CYS/USDC",
    "UPFI/USDC",
    "HOTTO/USDC",
    "CRY/USDC",
    "ASH/USDC",
    "BST/USDC",
    "AGTE/USDC",
    "HIMA/USDC",
    "GOATS/USDC",
    "HP/USDC",
    "FRIES/USDC",
    "CUBE/USDC",
    "SMBT/USDC",
    "FLOOF/USDC",
    "DOGETH/USDC",
    "OOAH/USDC",
    "PUSSY/USDC",
    "JESUS/USDC",
    "CATOMIAOU/USDC",
    "BITCH/USDC",
    "SHIBETOSHI/USDC",
    "KissMe/USDC",
    "DoggyStyle/USDC",
    "LEONIDAS/USDC",
    "WAGMI/USDC",
    "SLT/USDC",
    "CRAT/USDC",
    "GAMESHIB/USDC",
    "SAFE/USDC",
    "DEEZ/USDC",
    "NinjaDoge/USDC",
    "SHIBMOON/USDC",
    "GALAXY/USDC",
    "UNISOL/USDC",
    "POLE/USDC"
]

look good

**Comment by lmvdz** [comment]
Right, but the serum-vial link I posted in my previous comment is where the data of trades comes from. If serum vial isn't listening for all 156 markets then your list from raw GitHub will have pairs which won't be able to subscribe to serum vial for data

**Comment by lmvdz** [comment]
Found this RPC: https://free.rpcpool.com `serum-vial --endpoint https://free.rpcpool.com`

**Pull request closed without merging**
